'''
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Answer: 4613732
'''

def main(limit = 4000000):
	n1, n2 = 1, 2
	even_sum = 0
	while (n2 <= limit):
		if n2%2 == 0:
			even_sum += n2
		temp = n2 + n1
		n1 = n2
		n2 = temp
	return even_sum


if __name__ == '__main__':
	print(main())